In [ ]:
# Q1. Reverse the NumPy array: arr = np.array([1, 2, 3, 6, 4, 5]) )
import numpy as np

arr = np.array([i for i in range(1, 5 + 1)])
print("Reversed array: ")
print(np.flip(arr))



In [24]:
# Q2. Compare the following numpy arrays:
# arr1 = np.array([[1, 2], [3, 4]])
# arr2 = np.array([[1, 2], [3, 4]])

# arr2 = np.ndarray(shape=(2,1), dtype=float, order='C')
arr1 = np.array([[1,2], [3,4]])
arr2 = np.array([[1,2], [3,4]])
print(np.array_equal(arr1, arr2))
print(np.greater(arr1, arr2))
print(np.greater_equal(arr1, arr2))
print(np.less_equal(arr1, arr2))
print(np.less(arr1, arr2))


True
[[False False]
 [False False]]
[[ True  True]
 [ True  True]]
[[ True  True]
 [ True  True]]
[[False False]
 [False False]]


In [21]:
# Q3. Find the most frequent value and their indice(s) in the following arrays:
# i. x = np.array([1,2,3,4,5,1,2,1,1,1])
# ii. y = np.array([1, 1, 1, 2, 3, 4, 2, 4, 3, 3, ])
import numpy as np

x = np.array([1,2,3,4,5,1,2,1,1,1])
# print("Number of occurrences of each element: ", np.bincount(x))
mode_of_x = np.bincount(x).argmax()
print("Element with the highest frequency: ", mode_of_x)
print("Indices: ", [i for i in range(len(x)) if x[i] == mode_of_x])
print("Indices: ", np.where(x == mode_of_x)[0])

y = np.array([1,1,1,2,3,4,2,4,3,3])
# print("Number of occurrences of each element: ", np.bincount(y))
mode_of_y = np.bincount(y).argmax()
print("Element with the highest frequency: ", mode_of_y)
print("Indices: ", np.where(y == mode_of_y)[0])


Element with the highest frequency:  1
Indices:  [0, 5, 7, 8, 9]
Indices:  [0 5 7 8 9]
Element with the highest frequency:  1
Indices:  [0 1 2]


In [20]:
# 4. For the array gfg = np.matrix('[4, 1, 9; 12, 3, 1; 4, 5, 6]'),
# find i. Sum of all elements
# ii. Sum of all elements row-wise
# iii. Sum of all elements column-wise
matrix = np.matrix('[4, 1, 9; 12, 3, 1; 4, 5, 6]')
print("Original matrix:\n", matrix)
print("Sum of all elements:\n", matrix.sum())
print("Sum of all elements row-wise:\n", matrix.sum(axis=1))
print("Sum of all elements column-wise:\n", matrix.sum(axis=0))


Original matrix:
 [[ 4  1  9]
 [12  3  1]
 [ 4  5  6]]
Sum of all elements:
 45
Sum of all elements row-wise:
 [[14]
 [16]
 [15]]
Sum of all elements column-wise:
 [[20  9 16]]
