<a href="https://colab.research.google.com/github/Gojou-Satoru-8/BDA/blob/main/LABEVAL_MCA1_202301009.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [20]:
# Mutliply the following matrices and also find covariance between matrices using Numpy:
import numpy as np
p = np.matrix([[1,2], [2,3]]) # Or np.array([[1,2], [2,3]])
q = np.matrix([[4,5], [6,7]]) # Or np.array([[4,5], [6,7]])

print(f"The first matrix is:")
print(p)
print(f"The second matrix is:")
print(q)
print("------------------")

product = np.dot(p, q)  # Or np.matmul(p, q)
print(f"The product matrix of two the two matrices : ")
print(product)
print("------------------")
# If multiplying corresponding elements is desired:
print("Multiplication of corresponding elements of the numpy arrays/matrices:")
print(np.multiply(p, q))
print("------------------")

# Finding Covariance:
covariance = np.cov(p, q)
print(f"The covariance between matrices p and q using np.cov(p, q) is: ")
print(covariance)

The first matrix is:
[[1 2]
 [2 3]]
The second matrix is:
[[4 5]
 [6 7]]
------------------
The product matrix of two the two matrices : 
[[16 19]
 [26 31]]
------------------
Multiplication of corresponding elements of the numpy arrays/matrices:
[[ 4 10]
 [12 21]]
------------------
The covariance between matrices p and q using np.cov(p, q) is: 
[[0.5 0.5 0.5 0.5]
 [0.5 0.5 0.5 0.5]
 [0.5 0.5 0.5 0.5]
 [0.5 0.5 0.5 0.5]]
